#!/usr/bin/env python3
"""
Setup script for Chris Dunn Production
Converts 12-word phrase to wallet credentials
"""

import sys
from pathlib import Path

print("""
╔══════════════════════════════════════════════════════════════╗
║  Chris Dunn v2.0 - Production Setup                          ║
║  XRP/RLUSD Market Maker with Auto Profit Sweep               ║
╚══════════════════════════════════════════════════════════════╝

⚠️  SECURITY WARNING:
    This script helps convert your 12-word phrase to xrpl-py format.
    Your secret key will be stored in config/production.yaml.
    Run: chmod 600 config/production.yaml after setup.

""")

try:
    from xrpl.wallet import Wallet
except ImportError:
    print("❌ xrpl-py not installed.")
    print("Run: pip install xrpl-py")
    sys.exit(1)

# Get inputs
print("Step 1: Trading Wallet (Hot Wallet)")
print("-" * 50)
address = input("Trading wallet address (r...): ").strip()

print("\nStep 2: Convert 12-Word Phrase")
print("-" * 50)
print("Enter your 12-word seed phrase (space separated):")
phrase = input("> ").strip()

# Convert phrase to wallet
try:
    wallet = Wallet.from_seed(phrase)
    derived_address = wallet.classic_address
    secret = wallet.seed
    
    print(f"\n✅ Derived Address: {derived_address}")
    
    if derived_address != address:
        print(f"\n⚠️  WARNING: Derived address doesn't match provided address!")
        print(f"   Provided:  {address}")
        print(f"   Derived:   {derived_address}")
        confirm = input("Continue anyway? (yes/no): ").strip().lower()
        if confirm != 'yes':
            print("Setup cancelled.")
            sys.exit(0)
        address = derived_address
    
    print(f"   Secret:    {secret[:10]}...{secret[-5:]}")
    
except Exception as e:
    print(f"\n❌ Error converting phrase: {e}")
    sys.exit(1)

print("\nStep 3: Profit Vault Address")
print("-" * 50)
vault = input("Vault wallet address (r...) for profit sweeps: ").strip()

# Generate config
config_content = f"""# Chris Dunn Production Config
# Generated: Auto-generated by setup.py

wallet:
  # Trading wallet (hot) - limited funds for active MM
  address: "{address}"
  secret: "{secret}"
  
  # Profit vault (Xaman secured) - receives swept profits
  vault_address: "{vault}"

# Trading pair
trading:
  pair: "XRP/RLUSD"
  base: "XRP"
  quote: "RLUSD"
  quote_issuer: "rMxCKbEDwqr76QuOHsegZAHQZdWw8DYtT"  # Ripple RLUSD
  
# Market Making Parameters (Conservative Start)
market_maker:
  spread_pct: 0.8           # 0.8% spread
  order_size_xrp: 25        # Start small: 25 XRP per order
  max_orders_each_side: 2   # Max 2 bids + 2 asks
  rebalance_threshold: 0.05
  target_inventory: 0.5
  
# Profit Sweep
sweep:
  enabled: true
  threshold_xrp: 35         # Keep 35 XRP, sweep rest
  threshold_rlusd: 50       # Keep 50 RLUSD, sweep rest
  interval_minutes: 60

# Risk Management  
risk:
  portfolio_value: 300      # Conservative start
  position_limit_pct: 0.02
  daily_loss_limit_pct: 0.05
  max_consecutive_losses: 3
  
# XRPL Connection
xrpl:
  websocket_url: "wss://s1.ripple.com"
  fallback_url: "wss://s2.ripple.com"
  
# Telegram Alerts (using existing bot)
telegram:
  bot_token: "8350022484:AAE93G6trBzE6fhahPtdCKWZke6ZubGTaGQ"
  group_chat_id: "-1003885436287"
  alert_on_trade: true
  alert_on_profit_sweep: true
  alert_on_error: true
"""

# Write config
config_path = Path('config/production.yaml')
config_path.parent.mkdir(exist_ok=True)

with open(config_path, 'w') as f:
    f.write(config_content)

print(f"\n✅ Config saved to: {config_path}")
print("\nStep 4: Secure the config file")
print("-" * 50)
import os
os.chmod(config_path, 0o600)
print("   chmod 600 applied (owner read-only)")

print("""
╔══════════════════════════════════════════════════════════════╗
║  Setup Complete!                                             ║
╚══════════════════════════════════════════════════════════════╝

Next Steps:
1. Verify wallet has 30+ XRP and RLUSD trust line
2. Ensure RLUSD balance is > 0
3. Test run: python production_runner.py

Commands:
  python production_runner.py          # Start trading
  tail -f logs/production.log          # Watch logs
  
⚠️  IMPORTANT:
    - Start with small amounts (conservative settings in config)
    - Monitor Telegram for trade alerts
    - Profits auto-sweep to your vault every hour
    - Press Ctrl+C to stop gracefully

""")
